// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CinephileDbContext))]
    [Migration("20260805094644_AddGamification")]
    partial class AddGamification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Details")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("AchievementId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementId = 1,
                            Code = "FIRST_LOG",
                            Details = "Log your very first film.",
                            Name = "First Reel",
                            Points = 10
                        },
                        new
                        {
                            AchievementId = 2,
                            Code = "MARATHONER",
                            Details = "Watch 5 movies in a single week.",
                            Name = "Marathoner",
                            Points = 25
                        },
                        new
                        {
                            AchievementId = 3,
                            Code = "CENTURION",
                            Details = "Log 100 films watched.",
                            Name = "Centurion",
                            Points = 150
                        },
                        new
                        {
                            AchievementId = 4,
                            Code = "CRITIC_10",
                            Details = "Write 10 reviews.",
                            Name = "The Critic",
                            Points = 40
                        },
                        new
                        {
                            AchievementId = 5,
                            Code = "EXPLORER_8",
                            Details = "Watch a film from 8 different genres.",
                            Name = "Explorer",
                            Points = 35
                        },
                        new
                        {
                            AchievementId = 6,
                            Code = "DEVOTED_30",
                            Details = "Maintain a 30-day viewing streak.",
                            Name = "Devoted",
                            Points = 100
                        },
                        new
                        {
                            AchievementId = 7,
                            Code = "PROCRASTINATOR_20",
                            Details = "Keep 20 movies in your watchlist.",
                            Name = "Procrastinator",
                            Points = 20
                        },
                        new
                        {
                            AchievementId = 8,
                            Code = "TRUE_CINEPHILE_LVL20",
                            Details = "Reach Level 20.",
                            Name = "True Cinephile",
                            Points = 200
                        });
                });

            modelBuilder.Entity("backend.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("integer");

                    b.HasKey("LevelId");

                    b.HasIndex("LevelName")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            LevelName = "Rookie Critic",
                            PointsRequired = 0
                        },
                        new
                        {
                            LevelId = 2,
                            LevelName = "Popcorn Enthusiast",
                            PointsRequired = 50
                        },
                        new
                        {
                            LevelId = 3,
                            LevelName = "Casual Viewer",
                            PointsRequired = 120
                        },
                        new
                        {
                            LevelId = 4,
                            LevelName = "Weekend Watcher",
                            PointsRequired = 220
                        },
                        new
                        {
                            LevelId = 5,
                            LevelName = "Movie Night Regular",
                            PointsRequired = 350
                        },
                        new
                        {
                            LevelId = 6,
                            LevelName = "Screen Devotee",
                            PointsRequired = 520
                        },
                        new
                        {
                            LevelId = 7,
                            LevelName = "Genre Explorer",
                            PointsRequired = 730
                        },
                        new
                        {
                            LevelId = 8,
                            LevelName = "Film Aficionado",
                            PointsRequired = 990
                        },
                        new
                        {
                            LevelId = 9,
                            LevelName = "Reel Enthusiast",
                            PointsRequired = 1300
                        },
                        new
                        {
                            LevelId = 10,
                            LevelName = "Cinephile in Training",
                            PointsRequired = 1690
                        },
                        new
                        {
                            LevelId = 11,
                            LevelName = "Seasoned Viewer",
                            PointsRequired = 2150
                        },
                        new
                        {
                            LevelId = 12,
                            LevelName = "Seasoned Cinephile",
                            PointsRequired = 2690
                        },
                        new
                        {
                            LevelId = 13,
                            LevelName = "Film Scholar",
                            PointsRequired = 3320
                        },
                        new
                        {
                            LevelId = 14,
                            LevelName = "Cinema Connoisseur",
                            PointsRequired = 4050
                        },
                        new
                        {
                            LevelId = 15,
                            LevelName = "Master Cinephile",
                            PointsRequired = 4890
                        },
                        new
                        {
                            LevelId = 16,
                            LevelName = "Archive Keeper",
                            PointsRequired = 5850
                        },
                        new
                        {
                            LevelId = 17,
                            LevelName = "Legendary Viewer",
                            PointsRequired = 6940
                        },
                        new
                        {
                            LevelId = 18,
                            LevelName = "Cinema Sage",
                            PointsRequired = 8170
                        },
                        new
                        {
                            LevelId = 19,
                            LevelName = "Grand Cinephile",
                            PointsRequired = 9550
                        },
                        new
                        {
                            LevelId = 20,
                            LevelName = "True Cinephile",
                            PointsRequired = 11090
                        });
                });

            modelBuilder.Entity("backend.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Review")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("Rewatch")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WatchedDate")
                        .HasColumnType("date");

                    b.HasKey("LogId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "MovieId");

                    b.HasIndex("UserId", "WatchedDate");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("backend.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer");

                    b.HasKey("MovieId");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("backend.Models.Watchlist", b =>
                {
                    b.Property<int>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchlistId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("WatchlistId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.ToTable("WatchlistEntries");
                });

            modelBuilder.Entity("backend.Models.Log", b =>
                {
                    b.HasOne("backend.Models.Movie", "Movie")
                        .WithMany("Logs")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("backend.Models.UserAchievement", b =>
                {
                    b.HasOne("backend.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Watchlist", b =>
                {
                    b.HasOne("backend.Models.Movie", "Movie")
                        .WithMany("WatchlistEntries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("WatchlistEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("backend.Models.Level", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Movie", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("WatchlistEntries");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("UserAchievements");

                    b.Navigation("WatchlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
